name: deploy to firebase.functions.test

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: generate
      run: |
        cd functions
        yarn
        cd ..
    - name: choose project
      uses: w9jds/firebase-action@master
      with:
        args: use ${{ secrets.PROJECT_ID }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: set domain
      uses: w9jds/firebase-action@master
      with:
        args: target:apply hosting test ${{ secrets.TEST_DOMAIN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: deploy
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions:nuxtServer
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}