name: deploy to test env

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: generate
      run: |
        npm install yarn
        yarn
        yarn ci-generate cross-env META=\"noindex\" MES=\"${{ secrets.TEST_MES }}\" nuxt generate
    - name: deploy to Firebase Hosting
      run: |
        yarn add firebase-tools
        firebase --version
      # firebase deploy --only hosting:test --token ${{ secrets.FIREBASE_TOKEN }}

      # uses: w9jds/firebase-action@master
      # with:
      #   args: deploy --only hosting:test
      # env:
      #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}