name: deploy to test env

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: generate
      run: |
        yarn
        yarn ci-generate cross-env META=\"noindex\" MES=\"${{ secrets.TEST_MES }}\" nuxt generate
        yarn global add firebase-tools
        firebase --version
    # - name: choose project
    #   uses: w9jds/firebase-action@master
    #   with:
    #     args: use experiment-b0814
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    # - name: set domain
    #   uses: w9jds/firebase-action@master
    #   with:
    #     args: target:apply hosting test ${{ secrets.TEST_DOMAIN }}
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    # - name: deploy
    #   uses: w9jds/firebase-action@master
    #   with:
    #     args: deploy --only hosting:test
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    #     PROJECT_ID: experiment-b0814